In [1]:
import numpy as np


In [2]:
A=np.random.randint(1,10,(3,3))


In [3]:
A

array([[1, 8, 7],
       [9, 5, 6],
       [3, 3, 5]])

In [4]:
from numpy import linalg as LA
eigen_values,eigen_vector=LA.eig(A)

In [5]:
eigen_values

array([15.40638588, -5.80424527,  1.39785938])

In [6]:
eigen_vector

array([[-0.58272065, -0.77918176, -0.22574847],
       [-0.72060083,  0.62534076, -0.64784026],
       [-0.37572741,  0.04271682,  0.72755799]])

In [7]:
np.dot(eigen_values[0],eigen_vector[:,0])

array([ -8.97761918, -11.10185447,  -5.7886015 ])

In [8]:
np.dot(A,eigen_vector[:,0])

array([ -8.97761918, -11.10185447,  -5.7886015 ])

In [9]:
from numpy import linalg as LA
eigen_values1,eigen_vector=LA.eig(A)

In [10]:
np.dot(eigen_values1[0],eigen_vector[:,1])

array([-12.00437484,   9.63424099,   0.65811182])

In [11]:
np.dot(A,eigen_vector[:,1])

array([ 4.52256203, -3.62963112, -0.2479389 ])

### Linear Discriment Analysis